// <auto-generated />
namespace DatabaseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-rc1-19458-04")]
    public sealed partial class added_mcoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_mcoin));
        
        string IMigrationMetadata.Id
        {
            get { return "201910082014111_added_mcoin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
